version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres
    env_file:
      - /website/.env
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  main_app:
    build:
      context: ./website
    ports:
      - '8001:8000'
    depends_on:
      - postgres-db
    env_file:
      - /website/.env
    volumes:
      - static_volume:/app/static
    restart: on-failure:5
    healthcheck:
      test: curl -f http://localhost:8000/about || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s

  nginx:
    image: nginx:latest
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/static
    ports:
      - '80:80'
    depends_on:
      - main_app

volumes:
  pg_data:
  static_volume:


