# Generated by Django 4.2.4 on 2023-09-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_categories_options_alter_products_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewmodel',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, 'Good'), (4, '4'), (5, '5')]),
        ),
    ]
