from django.apps import apps
from django.db import connection



sql_migrate_0001 = '''
        BEGIN;
        --
        -- Create model Categories
        --
        CREATE TABLE "main_app_categories" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(20) NOT NULL, "slug" varchar(200) NOT NULL UNIQUE);
        --
        -- Create model Shops
        --
        CREATE TABLE "main_app_shops" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(20) NOT NULL, "slug" varchar(200) NOT NULL UNIQUE);
        --
        -- Create model Products
        --
        CREATE TABLE "main_app_products" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" text NOT NULL, "photo" text NOT NULL, "previous_price" double precision NOT NULL, "link" text NULL, "cat_id" bigint NOT NULL, "shop_id" bigint NOT NULL);
        CREATE INDEX "main_app_categories_name_9d1b12d2" ON "main_app_categories" ("name");
        CREATE INDEX "main_app_categories_name_9d1b12d2_like" ON "main_app_categories" ("name" varchar_pattern_ops);
        CREATE INDEX "main_app_categories_slug_201a0723_like" ON "main_app_categories" ("slug" varchar_pattern_ops);
        CREATE INDEX "main_app_shops_name_69b05fd9" ON "main_app_shops" ("name");
        CREATE INDEX "main_app_shops_name_69b05fd9_like" ON "main_app_shops" ("name" varchar_pattern_ops);
        CREATE INDEX "main_app_shops_slug_dfa368a5_like" ON "main_app_shops" ("slug" varchar_pattern_ops);
        ALTER TABLE "main_app_products" ADD CONSTRAINT "main_app_products_cat_id_ac3d1de4_fk_main_app_categories_id" FOREIGN KEY ("cat_id") REFERENCES "main_app_categories" ("id") DEFERRABLE INITIALLY DEFERRED;
        ALTER TABLE "main_app_products" ADD CONSTRAINT "main_app_products_shop_id_5ffd4812_fk_main_app_shops_id" FOREIGN KEY ("shop_id") REFERENCES "main_app_shops" ("id") DEFERRABLE INITIALLY DEFERRED;
        CREATE INDEX "main_app_products_name_513522dc" ON "main_app_products" ("name");
        CREATE INDEX "main_app_products_name_513522dc_like" ON "main_app_products" ("name" text_pattern_ops);
        CREATE INDEX "main_app_products_cat_id_ac3d1de4" ON "main_app_products" ("cat_id");
        CREATE INDEX "main_app_products_shop_id_5ffd4812" ON "main_app_products" ("shop_id");
        COMMIT;
        '''

def refresh_tables():
    '''
    Удаление и повторное создание таблиц Shops, Categories, Products
    '''
    with connection.cursor() as cursor:
        removed_tables = []
        exceptions = []
        for model in apps.get_models():
            if model.__name__ in ('Shops', 'Categories', 'Products'):
                try:
                    model.objects.all().delete()
                    cursor.execute(f'DROP TABLE IF EXISTS {model._meta.db_table} CASCADE')
                    print(f"Dropped table {model._meta.db_table} from model {model.__name__}")
                except Exception as e:
                    exceptions.append([model._meta.db_table, str(e)])
                    print(e)
                    continue
                removed_tables.append(model._meta.db_table)
        print(f"Removed {len(removed_tables)} tables")
        cursor.execute(sql_migrate_0001)

